name: mvn package

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17.0.4'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn package
    - uses: actions/upload-artifact@v3
      with:
        name: StaffChat-latest
        path: /home/runner/work/StaffChat/StaffChat/target/StaffChat-1.0.jar
